version: "3"
services:
#  admin-api:
#    image: admin-api:latest
#    network_mode: host
#    build:
#      context: .
#    container_name: admin-api
#    environment:
#      - DATABASE_HOST:database
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db_app
#    expose:
#      - 8080
#    ports:
#      - 8080:8080
#    restart: unless-stopped
#    depends_on:
#      - database
#    links:
#      - database

  database:
    image: postgres:13
    network_mode: bridge
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=db_app
    restart: always