version: "3"
services:
  app:
    build:
      context: .
    container_name: admin-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db_app
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=db_app
    restart: always